import * as fs from 'fs';
import * as path from 'path';

const shinkaViemPath = path.join(
  __dirname,
  '../../dist/libs/shinkai-viem/shinkai-viem.js',
);
const shinkaiViemContent = fs.readFileSync(shinkaViemPath, 'utf-8');

const outputPath = path.join(
  __dirname,
  'src/bundled-resources/shinkai-viem.ts',
);
const outputContent = `// autogenerated
export const viemScriptContent = "${Buffer.from(shinkaiViemContent).toString('base64')}";
`;

const outputDir = path.dirname(outputPath);
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(outputPath, outputContent);
