name: Build Shinkai Tools

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Make script executable
        run: chmod +x ./build-tool.sh

      - name: Run build script
        run: ./build-tool.sh
        env:
          SHINKAI_NODE_ADDR: ${{ secrets.SHINKAI_NODE_ADDR }}
          GITHUB_LOCATION: "https://raw.githubusercontent.com/dcSpark/shinkai-tools/refs/heads/"
          GITHUB_BRANCH: "main"

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add packages/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-build tools" && git push)