name: Build Shinkai Tools

on:
  workflow_dispatch:

jobs:
  build_tools:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq coreutils

      - name: Make script executable
        run: |
          chmod +x ./.github/build_tool.sh
          chmod +x ./.github/run_node.sh

      - name: Run node in background
        id: run_node
        run: |
          ./.github/run_node.sh &
          timeout 60 bash -c 'until curl -s --location "http://127.0.0.1:9550/v2/health_check" | jq -e ".status == \"ok\"" > /dev/null; do sleep 1; done'
          ./.github/build_tool.sh
        env:
          INITIAL_AGENT_NAMES: ${{ secrets.INITIAL_AGENT_NAMES }}
          INITIAL_AGENT_URLS: ${{ secrets.INITIAL_AGENT_URLS }}
          INITIAL_AGENT_MODELS: ${{ secrets.INITIAL_AGENT_MODELS }}
          INITIAL_AGENT_API_KEYS: ${{ secrets.INITIAL_AGENT_API_KEYS }}
          API_V2_KEY: ${{ secrets.API_V2_KEY }}
          EMBEDDINGS_SERVER_URL: ${{ secrets.EMBEDDINGS_SERVER_URL }}
          SHINKAI_NODE_ADDR: "http://localhost:9550"
          GITHUB_LOCATION: "https://raw.githubusercontent.com/dcSpark/shinkai-tools/"
          BEARER_TOKEN: ${{ secrets.API_V2_KEY }}          

      - name: Commit and push if changed
        if: steps.run_node.outcome == 'success'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add packages/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-build tools" && git push)