name: Build Shinkai Tools

on:
  workflow_dispatch:

jobs:
  build_tools:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq coreutils

      - name: Make script executable
        run: |
          chmod +x ./.github/build_tool.sh
          chmod +x ./.github/run_node.sh

      - name: Run node in background
        id: run_node
        env:
          INITIAL_AGENT_NAMES: ${{ secrets.INITIAL_AGENT_NAMES }}
          INITIAL_AGENT_URLS: ${{ secrets.INITIAL_AGENT_URLS }}
          INITIAL_AGENT_MODELS: ${{ secrets.INITIAL_AGENT_MODELS }}
          INITIAL_AGENT_API_KEYS: ${{ secrets.INITIAL_AGENT_API_KEYS }}
          API_V2_KEY: ${{ secrets.API_V2_KEY }}
          EMBEDDINGS_SERVER_URL: ${{ secrets.EMBEDDINGS_SERVER_URL }}
          SHINKAI_NODE_ADDR: "http://localhost:9550"
          BEARER_TOKEN: ${{ secrets.API_V2_KEY }}
          INITIALIZATION_DATA: ${{ secrets.INITIALIZATION_DATA }}
        run: |
          docker run -d -p 9550:9550 -p 9551:9551 -p 9552:9552 -p 9553:9553 \
          -e NODE_API_IP="0.0.0.0" \
          -e NODE_IP="0.0.0.0" \
          -e NODE_API_PORT="9550" \
          -e NODE_WS_PORT="9551" \
          -e NODE_PORT="9552" \
          -e NODE_HTTPS_PORT="9553" \
          -e IDENTITY_SECRET_KEY="df3f619804a92fdb4057192dc43dd748ea778adc52bc498ce80524c014b81119" \
          -e ENCRYPTION_SECRET_KEY="d83f619804a92fdb4057192dc43dd748ea778adc52bc498ce80524c014b81159" \
          -e PING_INTERVAL_SECS="0" \
          -e GLOBAL_IDENTITY_NAME="@@localhost.arb-sep-shinkai" \
          -e RUST_LOG=debug,error,info \
          -e STARTING_NUM_QR_PROFILES="1" \
          -e STARTING_NUM_QR_DEVICES="1" \
          -e FIRST_DEVICE_NEEDS_REGISTRATION_CODE="false" \
          -e LOG_SIMPLE="true" \
          -e NO_SECRET_FILE="true" \
          -e PROXY_IDENTITY="@@relayer_pub_01.arb-sep-shinkai" \
          -e SHINKAI_TOOLS_RUNNER_DENO_BINARY_PATH="./shinkai-tools-runner-resources/deno" \
          -e SHINKAI_TOOLS_RUNNER_UV_BINARY_PATH="./shinkai-tools-runner-resources/uv" \
          -e SHINKAI_VERSION="0.9.3" \
          -e LOG_ALL=1 \
          -e INITIAL_AGENT_NAMES="$INITIAL_AGENT_NAMES" \
          -e INITIAL_AGENT_URLS="$INITIAL_AGENT_URLS" \
          -e INITIAL_AGENT_MODELS="$INITIAL_AGENT_MODELS" \
          -e INITIAL_AGENT_API_KEYS="$INITIAL_AGENT_API_KEYS" \
          -e API_V2_KEY="$API_V2_KEY" \
          -e EMBEDDINGS_SERVER_URL="$EMBEDDINGS_SERVER_URL" \
          guillevalin/shinkai-node:latest
          timeout 60 bash -c 'until curl -s --location "$SHINKAI_NODE_ADDR/v2/health_check" | jq -e ".status == \"ok\"" > /dev/null; do sleep 1; done'
            curl --location "$SHINKAI_NODE_ADDR/v2/initial_registration" \
          --header 'Content-Type: application/json; charset=utf-8' \
            --data "$INITIALIZATION_DATA"
          ./.github/build_tool.sh
          if jq -e '.[] | select(.description == "")' packages/directory.json > /dev/null; then
            echo "Error: Empty descriptions found in packages/directory.json"
            exit 1
          fi

      - name: Commit and push if changed
        if: steps.run_node.outcome == 'success'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add packages/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-build tools" && git push)